### ISSUE TITLE
Aggiungere comando: prima build in cui è rientrata una certa branch

### ISSUE THREAD

**Issue by gbeccari** [mitechsrl/mitech-cli#3]
Aggiungere un comando che ritorni qual è la versione della prima build che contiene la merge di una branch.
Confrontando questa versione con quella dell'ultimo deploy, è possibile sapere se le modifiche apportate dalla branch sono già state deployate.

Guardare **mitech git merged**

**Comment by ivanvaccari** [comment]
Aggiunto comando "mitech git merge-tag".

Mostra la lista delle commit successive alla merge di una branch, e specifica se vi sono tag che la contengono. Non mostra solo il primo tag che la contiene, ma tutti i tag che la contengono (quindi anche il primo successivo).

Nota: il comando funziona solo se la branch è completamente mergiata.
